import type { Fleet, Profile, Vehicle, DriverCompliance, DriverDocument, TrainingProgram, Assignment, ComplianceRequirement, Notification, CompletionRecord, DriverStats } from '../types/database'

const FLEET_ID = 'demo-fleet-baldor'
const now = new Date().toISOString()

export const demoFleet: Fleet = {
  id: FLEET_ID,
  company_name: 'Baldor Food Company',
  locations: 'Bronx, NY; Newark, NJ; Boston, MA',
  cargo_type: 'Perishable Foods (Refrigerated)',
  cdl_status: 'Class A & B Required',
  vehicle_types: 'Refrigerated Trucks, Delivery Vans, Box Trucks',
  key_risk_areas: 'Temperature Control, Loading Dock Safety, Route Planning',
  operation_type: 'Regional Distribution',
  states_of_operation: 'NY, NJ, CT, MA, PA',
  onboarding_completed: true,
  compliance_profile_configured: true,
  logo_url: null,
  primary_color: '#16a34a',
  secondary_color: '#1e293b',
  default_language: 'en',
  created_at: '2024-01-15T00:00:00Z',
  updated_at: now,
}

export const demoProfiles: Profile[] = [
  {
    id: 'demo-user-jeremyw',
    email: 'jeremyw@baldorfood.com',
    name: 'Jeremy Williams',
    role: 'ADMIN',
    fleet_id: FLEET_ID,
    location_id: 'loc-bronx',
    phone: '(212) 555-0100',
    preferred_language: 'en',
    timezone: 'America/New_York',
    prefer_email: true,
    prefer_sms: true,
    prefer_push: true,
    employee_id: 'BFC-001',
    hire_date: '2020-03-15',
    is_active: true,
    last_login_at: now,
    created_at: '2020-03-15T00:00:00Z',
    updated_at: now,
  },
  {
    id: 'demo-driver-001',
    email: 'mrodriguez@baldorfood.com',
    name: 'Marco Rodriguez',
    role: 'DRIVER',
    fleet_id: FLEET_ID,
    location_id: 'loc-bronx',
    phone: '(718) 555-0201',
    preferred_language: 'en',
    timezone: 'America/New_York',
    prefer_email: true,
    prefer_sms: true,
    prefer_push: false,
    employee_id: 'BFC-102',
    hire_date: '2022-06-01',
    is_active: true,
    last_login_at: '2026-04-03T14:30:00Z',
    created_at: '2022-06-01T00:00:00Z',
    updated_at: now,
  },
  {
    id: 'demo-driver-002',
    email: 'sjohnson@baldorfood.com',
    name: 'Sarah Johnson',
    role: 'DRIVER',
    fleet_id: FLEET_ID,
    location_id: 'loc-bronx',
    phone: '(718) 555-0202',
    preferred_language: 'en',
    timezone: 'America/New_York',
    prefer_email: true,
    prefer_sms: false,
    prefer_push: true,
    employee_id: 'BFC-103',
    hire_date: '2023-01-10',
    is_active: true,
    last_login_at: '2026-04-02T09:00:00Z',
    created_at: '2023-01-10T00:00:00Z',
    updated_at: now,
  },
  {
    id: 'demo-driver-003',
    email: 'dpatel@baldorfood.com',
    name: 'Dev Patel',
    role: 'DRIVER',
    fleet_id: FLEET_ID,
    location_id: 'loc-newark',
    phone: '(973) 555-0301',
    preferred_language: 'en',
    timezone: 'America/New_York',
    prefer_email: true,
    prefer_sms: true,
    prefer_push: true,
    employee_id: 'BFC-104',
    hire_date: '2023-08-20',
    is_active: true,
    last_login_at: '2026-04-01T11:15:00Z',
    created_at: '2023-08-20T00:00:00Z',
    updated_at: now,
  },
  {
    id: 'demo-driver-004',
    email: 'tlee@baldorfood.com',
    name: 'Tony Lee',
    role: 'DRIVER',
    fleet_id: FLEET_ID,
    location_id: 'loc-newark',
    phone: '(973) 555-0302',
    preferred_language: 'en',
    timezone: 'America/New_York',
    prefer_email: false,
    prefer_sms: true,
    prefer_push: true,
    employee_id: 'BFC-105',
    hire_date: '2021-11-05',
    is_active: true,
    last_login_at: '2026-03-30T08:45:00Z',
    created_at: '2021-11-05T00:00:00Z',
    updated_at: now,
  },
  {
    id: 'demo-driver-005',
    email: 'agarcia@baldorfood.com',
    name: 'Ana Garcia',
    role: 'DRIVER',
    fleet_id: FLEET_ID,
    location_id: 'loc-boston',
    phone: '(617) 555-0401',
    preferred_language: 'es',
    timezone: 'America/New_York',
    prefer_email: true,
    prefer_sms: true,
    prefer_push: false,
    employee_id: 'BFC-106',
    hire_date: '2024-02-14',
    is_active: true,
    last_login_at: '2026-04-03T16:00:00Z',
    created_at: '2024-02-14T00:00:00Z',
    updated_at: now,
  },
  {
    id: 'demo-driver-006',
    email: 'rthompson@baldorfood.com',
    name: 'Ray Thompson',
    role: 'DRIVER',
    fleet_id: FLEET_ID,
    location_id: 'loc-bronx',
    phone: '(718) 555-0203',
    preferred_language: 'en',
    timezone: 'America/New_York',
    prefer_email: true,
    prefer_sms: false,
    prefer_push: false,
    employee_id: 'BFC-107',
    hire_date: '2019-07-22',
    is_active: false,
    last_login_at: '2025-12-01T10:00:00Z',
    created_at: '2019-07-22T00:00:00Z',
    updated_at: now,
  },
  {
    id: 'demo-sup-001',
    email: 'kbrown@baldorfood.com',
    name: 'Karen Brown',
    role: 'SUPERVISOR',
    fleet_id: FLEET_ID,
    location_id: 'loc-bronx',
    phone: '(212) 555-0102',
    preferred_language: 'en',
    timezone: 'America/New_York',
    prefer_email: true,
    prefer_sms: true,
    prefer_push: true,
    employee_id: 'BFC-050',
    hire_date: '2021-04-01',
    is_active: true,
    last_login_at: '2026-04-03T17:30:00Z',
    created_at: '2021-04-01T00:00:00Z',
    updated_at: now,
  },
  {
    id: 'demo-mgr-001',
    email: 'jmartinez@baldorfood.com',
    name: 'Jose Martinez',
    role: 'BRANCH_MANAGER',
    fleet_id: FLEET_ID,
    location_id: 'loc-newark',
    phone: '(973) 555-0100',
    preferred_language: 'en',
    timezone: 'America/New_York',
    prefer_email: true,
    prefer_sms: true,
    prefer_push: true,
    employee_id: 'BFC-025',
    hire_date: '2020-08-10',
    is_active: true,
    last_login_at: '2026-04-03T08:00:00Z',
    created_at: '2020-08-10T00:00:00Z',
    updated_at: now,
  },
  {
    id: 'demo-coach-001',
    email: 'lwilson@baldorfood.com',
    name: 'Lisa Wilson',
    role: 'DRIVER_COACH',
    fleet_id: FLEET_ID,
    location_id: 'loc-bronx',
    phone: '(212) 555-0103',
    preferred_language: 'en',
    timezone: 'America/New_York',
    prefer_email: true,
    prefer_sms: false,
    prefer_push: true,
    employee_id: 'BFC-040',
    hire_date: '2022-01-15',
    is_active: true,
    last_login_at: '2026-04-02T13:00:00Z',
    created_at: '2022-01-15T00:00:00Z',
    updated_at: now,
  },
]

export const demoVehicles: Vehicle[] = [
  {
    id: 'veh-001',
    fleet_id: FLEET_ID,
    vehicle_number: 'BFC-R101',
    vehicle_type: 'refrigerated_truck',
    make: 'Freightliner',
    model: 'M2 106',
    year: 2023,
    license_plate: 'NY-TRK-4521',
    has_temperature_monitoring: true,
    last_inspection_date: '2026-02-15',
    next_inspection_due: '2026-08-15',
    assigned_route: 'Bronx → Manhattan → Brooklyn',
    assigned_driver_id: 'demo-driver-001',
    is_active: true,
    notes: null,
    created_at: '2023-03-01T00:00:00Z',
    profiles: demoProfiles.find(p => p.id === 'demo-driver-001'),
  },
  {
    id: 'veh-002',
    fleet_id: FLEET_ID,
    vehicle_number: 'BFC-R102',
    vehicle_type: 'refrigerated_truck',
    make: 'Kenworth',
    model: 'T370',
    year: 2022,
    license_plate: 'NY-TRK-4522',
    has_temperature_monitoring: true,
    last_inspection_date: '2026-01-20',
    next_inspection_due: '2026-07-20',
    assigned_route: 'Bronx → Queens → Long Island',
    assigned_driver_id: 'demo-driver-002',
    is_active: true,
    notes: null,
    created_at: '2022-06-15T00:00:00Z',
    profiles: demoProfiles.find(p => p.id === 'demo-driver-002'),
  },
  {
    id: 'veh-003',
    fleet_id: FLEET_ID,
    vehicle_number: 'BFC-D201',
    vehicle_type: 'delivery_van',
    make: 'Ford',
    model: 'E-Transit',
    year: 2024,
    license_plate: 'NJ-VAN-8810',
    has_temperature_monitoring: false,
    last_inspection_date: '2026-03-01',
    next_inspection_due: '2026-09-01',
    assigned_route: 'Newark → Jersey City → Hoboken',
    assigned_driver_id: 'demo-driver-003',
    is_active: true,
    notes: null,
    created_at: '2024-01-10T00:00:00Z',
    profiles: demoProfiles.find(p => p.id === 'demo-driver-003'),
  },
  {
    id: 'veh-004',
    fleet_id: FLEET_ID,
    vehicle_number: 'BFC-R103',
    vehicle_type: 'refrigerated_truck',
    make: 'International',
    model: 'MV607',
    year: 2023,
    license_plate: 'NJ-TRK-3302',
    has_temperature_monitoring: true,
    last_inspection_date: '2025-12-10',
    next_inspection_due: '2026-06-10',
    assigned_route: 'Newark → Elizabeth → Woodbridge',
    assigned_driver_id: 'demo-driver-004',
    is_active: true,
    notes: null,
    created_at: '2023-05-20T00:00:00Z',
    profiles: demoProfiles.find(p => p.id === 'demo-driver-004'),
  },
  {
    id: 'veh-005',
    fleet_id: FLEET_ID,
    vehicle_number: 'BFC-B301',
    vehicle_type: 'box_truck',
    make: 'Isuzu',
    model: 'NPR-HD',
    year: 2021,
    license_plate: 'MA-BOX-2241',
    has_temperature_monitoring: false,
    last_inspection_date: '2026-03-15',
    next_inspection_due: '2026-09-15',
    assigned_route: 'Boston → Cambridge → Somerville',
    assigned_driver_id: 'demo-driver-005',
    is_active: true,
    notes: null,
    created_at: '2021-09-01T00:00:00Z',
    profiles: demoProfiles.find(p => p.id === 'demo-driver-005'),
  },
  {
    id: 'veh-006',
    fleet_id: FLEET_ID,
    vehicle_number: 'BFC-R104',
    vehicle_type: 'refrigerated_truck',
    make: 'Peterbilt',
    model: '536',
    year: 2020,
    license_plate: 'NY-TRK-4523',
    has_temperature_monitoring: true,
    last_inspection_date: '2025-11-01',
    next_inspection_due: '2026-05-01',
    assigned_route: null,
    assigned_driver_id: null,
    is_active: false,
    notes: 'Undergoing maintenance',
    created_at: '2020-04-01T00:00:00Z',
  },
]

export const demoComplianceRequirements: ComplianceRequirement[] = [
  { id: 'req-cdl', name: 'CDL Verification', description: 'Valid Commercial Driver License required', regulatory_body: 'FMCSA', required_hours: null, renewal_period: 365, applies_to: ['DRIVER'], is_active: true, fleet_id: FLEET_ID, alert_days: [90, 60, 30], created_at: '2024-01-01T00:00:00Z' },
  { id: 'req-medical', name: 'Medical Card', description: 'DOT medical certificate', regulatory_body: 'FMCSA', required_hours: null, renewal_period: 730, applies_to: ['DRIVER'], is_active: true, fleet_id: FLEET_ID, alert_days: [90, 60, 30], created_at: '2024-01-01T00:00:00Z' },
  { id: 'req-drug', name: 'Drug & Alcohol Testing', description: 'Pre-employment and random testing', regulatory_body: 'FMCSA', required_hours: null, renewal_period: 365, applies_to: ['DRIVER'], is_active: true, fleet_id: FLEET_ID, alert_days: [30, 14], created_at: '2024-01-01T00:00:00Z' },
  { id: 'req-hazmat', name: 'HazMat Endorsement', description: 'Hazardous materials handling certification', regulatory_body: 'FMCSA/TSA', required_hours: 8, renewal_period: 365, applies_to: ['DRIVER'], is_active: true, fleet_id: FLEET_ID, alert_days: [60, 30], created_at: '2024-01-01T00:00:00Z' },
  { id: 'req-food', name: 'Food Handler Certification', description: 'Safe food transport handling', regulatory_body: 'FDA', required_hours: 4, renewal_period: 365, applies_to: ['DRIVER'], is_active: true, fleet_id: FLEET_ID, alert_days: [60, 30], created_at: '2024-01-01T00:00:00Z' },
  { id: 'req-mvr', name: 'Motor Vehicle Record', description: 'Annual MVR check', regulatory_body: 'FMCSA', required_hours: null, renewal_period: 365, applies_to: ['DRIVER'], is_active: true, fleet_id: FLEET_ID, alert_days: [30, 14], created_at: '2024-01-01T00:00:00Z' },
]

export const demoComplianceRecords: DriverCompliance[] = [
  { id: 'comp-001', user_id: 'demo-driver-001', requirement_id: 'req-cdl', status: 'COMPLIANT', completed_date: '2025-06-01', expiration_date: '2027-06-01', hours_completed: null, certificate_url: null, verified_by: 'demo-sup-001', verified_at: '2025-06-05T00:00:00Z', notes: null, created_at: '2025-06-01T00:00:00Z', compliance_requirements: demoComplianceRequirements[0], profiles: demoProfiles[1] },
  { id: 'comp-002', user_id: 'demo-driver-001', requirement_id: 'req-medical', status: 'COMPLIANT', completed_date: '2025-08-15', expiration_date: '2027-08-15', hours_completed: null, certificate_url: null, verified_by: 'demo-sup-001', verified_at: '2025-08-16T00:00:00Z', notes: null, created_at: '2025-08-15T00:00:00Z', compliance_requirements: demoComplianceRequirements[1], profiles: demoProfiles[1] },
  { id: 'comp-003', user_id: 'demo-driver-002', requirement_id: 'req-cdl', status: 'COMPLIANT', completed_date: '2025-03-10', expiration_date: '2027-03-10', hours_completed: null, certificate_url: null, verified_by: 'demo-sup-001', verified_at: '2025-03-11T00:00:00Z', notes: null, created_at: '2025-03-10T00:00:00Z', compliance_requirements: demoComplianceRequirements[0], profiles: demoProfiles[2] },
  { id: 'comp-004', user_id: 'demo-driver-002', requirement_id: 'req-medical', status: 'EXPIRING_SOON', completed_date: '2024-05-20', expiration_date: '2026-05-20', hours_completed: null, certificate_url: null, verified_by: 'demo-sup-001', verified_at: '2024-05-21T00:00:00Z', notes: 'Renewal appointment scheduled', created_at: '2024-05-20T00:00:00Z', compliance_requirements: demoComplianceRequirements[1], profiles: demoProfiles[2] },
  { id: 'comp-005', user_id: 'demo-driver-003', requirement_id: 'req-cdl', status: 'COMPLIANT', completed_date: '2025-09-01', expiration_date: '2027-09-01', hours_completed: null, certificate_url: null, verified_by: 'demo-mgr-001', verified_at: '2025-09-02T00:00:00Z', notes: null, created_at: '2025-09-01T00:00:00Z', compliance_requirements: demoComplianceRequirements[0], profiles: demoProfiles[3] },
  { id: 'comp-006', user_id: 'demo-driver-004', requirement_id: 'req-cdl', status: 'EXPIRED', completed_date: '2024-01-15', expiration_date: '2026-01-15', hours_completed: null, certificate_url: null, verified_by: null, verified_at: null, notes: 'Needs immediate renewal', created_at: '2024-01-15T00:00:00Z', compliance_requirements: demoComplianceRequirements[0], profiles: demoProfiles[4] },
  { id: 'comp-007', user_id: 'demo-driver-005', requirement_id: 'req-food', status: 'COMPLIANT', completed_date: '2025-11-01', expiration_date: '2026-11-01', hours_completed: 4, certificate_url: null, verified_by: 'demo-coach-001', verified_at: '2025-11-02T00:00:00Z', notes: null, created_at: '2025-11-01T00:00:00Z', compliance_requirements: demoComplianceRequirements[4], profiles: demoProfiles[5] },
  { id: 'comp-008', user_id: 'demo-driver-003', requirement_id: 'req-drug', status: 'COMPLIANT', completed_date: '2026-02-01', expiration_date: '2027-02-01', hours_completed: null, certificate_url: null, verified_by: 'demo-mgr-001', verified_at: '2026-02-02T00:00:00Z', notes: 'Random test - passed', created_at: '2026-02-01T00:00:00Z', compliance_requirements: demoComplianceRequirements[2], profiles: demoProfiles[3] },
]

export const demoDocuments: DriverDocument[] = [
  { id: 'doc-001', user_id: 'demo-driver-001', fleet_id: FLEET_ID, document_type: 'CDL', document_number: 'CDL-NY-78945', issued_date: '2025-06-01', expiration_date: '2027-06-01', issuing_state: 'NY', cdl_class: 'A', endorsements: ['T', 'N'], restrictions: [], status: 'valid', created_at: '2025-06-01T00:00:00Z', profiles: demoProfiles[1] },
  { id: 'doc-002', user_id: 'demo-driver-001', fleet_id: FLEET_ID, document_type: 'MEDICAL_CARD', document_number: 'MC-2025-4421', issued_date: '2025-08-15', expiration_date: '2027-08-15', issuing_state: 'NY', cdl_class: null, endorsements: [], restrictions: [], status: 'valid', created_at: '2025-08-15T00:00:00Z', profiles: demoProfiles[1] },
  { id: 'doc-003', user_id: 'demo-driver-002', fleet_id: FLEET_ID, document_type: 'CDL', document_number: 'CDL-NY-66231', issued_date: '2025-03-10', expiration_date: '2027-03-10', issuing_state: 'NY', cdl_class: 'B', endorsements: ['P'], restrictions: ['L'], status: 'valid', created_at: '2025-03-10T00:00:00Z', profiles: demoProfiles[2] },
  { id: 'doc-004', user_id: 'demo-driver-002', fleet_id: FLEET_ID, document_type: 'MEDICAL_CARD', document_number: 'MC-2024-3310', issued_date: '2024-05-20', expiration_date: '2026-05-20', issuing_state: 'NY', cdl_class: null, endorsements: [], restrictions: [], status: 'expiring', created_at: '2024-05-20T00:00:00Z', profiles: demoProfiles[2] },
  { id: 'doc-005', user_id: 'demo-driver-003', fleet_id: FLEET_ID, document_type: 'CDL', document_number: 'CDL-NJ-55102', issued_date: '2025-09-01', expiration_date: '2027-09-01', issuing_state: 'NJ', cdl_class: 'A', endorsements: ['T', 'H', 'N'], restrictions: [], status: 'valid', created_at: '2025-09-01T00:00:00Z', profiles: demoProfiles[3] },
  { id: 'doc-006', user_id: 'demo-driver-004', fleet_id: FLEET_ID, document_type: 'CDL', document_number: 'CDL-NJ-44098', issued_date: '2024-01-15', expiration_date: '2026-01-15', issuing_state: 'NJ', cdl_class: 'A', endorsements: ['T'], restrictions: [], status: 'expired', created_at: '2024-01-15T00:00:00Z', profiles: demoProfiles[4] },
  { id: 'doc-007', user_id: 'demo-driver-005', fleet_id: FLEET_ID, document_type: 'CDL', document_number: 'CDL-MA-99001', issued_date: '2025-12-01', expiration_date: '2027-12-01', issuing_state: 'MA', cdl_class: 'B', endorsements: ['P'], restrictions: [], status: 'valid', created_at: '2025-12-01T00:00:00Z', profiles: demoProfiles[5] },
  { id: 'doc-008', user_id: 'demo-driver-005', fleet_id: FLEET_ID, document_type: 'FOOD_HANDLER_CERT', document_number: 'FH-MA-2025-445', issued_date: '2025-11-01', expiration_date: '2026-11-01', issuing_state: 'MA', cdl_class: null, endorsements: [], restrictions: [], status: 'valid', created_at: '2025-11-01T00:00:00Z', profiles: demoProfiles[5] },
]

export const demoTrainingPrograms: TrainingProgram[] = [
  { id: 'tp-001', program_name: 'New Driver Orientation', description: 'Comprehensive onboarding program for new fleet drivers covering company policies, safety procedures, and equipment familiarization.', is_recommended: true, fleet_id: FLEET_ID, is_template: false, template_category: 'Onboarding', estimated_duration: 480, compliance_requirement_id: null, created_at: '2024-01-15T00:00:00Z', updated_at: now },
  { id: 'tp-002', program_name: 'Refrigerated Transport Safety', description: 'Cold chain management, temperature monitoring, and proper loading/unloading procedures for perishable goods.', is_recommended: true, fleet_id: FLEET_ID, is_template: false, template_category: 'Safety', estimated_duration: 240, compliance_requirement_id: 'req-food', created_at: '2024-02-01T00:00:00Z', updated_at: now },
  { id: 'tp-003', program_name: 'Defensive Driving', description: 'Advanced driving techniques for urban delivery environments including hazard recognition and accident prevention.', is_recommended: true, fleet_id: FLEET_ID, is_template: false, template_category: 'Safety', estimated_duration: 180, compliance_requirement_id: null, created_at: '2024-03-01T00:00:00Z', updated_at: now },
  { id: 'tp-004', program_name: 'HazMat Awareness', description: 'Identification, handling, and emergency response procedures for hazardous materials encountered during food distribution.', is_recommended: false, fleet_id: FLEET_ID, is_template: false, template_category: 'Compliance', estimated_duration: 360, compliance_requirement_id: 'req-hazmat', created_at: '2024-04-01T00:00:00Z', updated_at: now },
  { id: 'tp-005', program_name: 'DOT Hours of Service', description: 'Understanding and compliance with FMCSA hours of service regulations, ELD usage, and record keeping.', is_recommended: true, fleet_id: FLEET_ID, is_template: false, template_category: 'Compliance', estimated_duration: 120, compliance_requirement_id: null, created_at: '2024-05-01T00:00:00Z', updated_at: now },
  { id: 'tp-006', program_name: 'Loading Dock Safety', description: 'Safe practices for loading dock operations including forklift awareness, pallet handling, and slip/trip prevention.', is_recommended: false, fleet_id: FLEET_ID, is_template: false, template_category: 'Safety', estimated_duration: 90, compliance_requirement_id: null, created_at: '2024-06-01T00:00:00Z', updated_at: now },
]

export const demoAssignments: Assignment[] = [
  { id: 'asgn-001', status: 'completed', due_date: '2026-02-15', assigned_date: '2026-01-15', user_id: 'demo-driver-001', fleet_id: FLEET_ID, module_id: null, training_program_id: 'tp-001', assigned_by: 'demo-user-jeremyw', priority: 'high', reminders_sent: 0, created_at: '2026-01-15T00:00:00Z', profiles: demoProfiles[1], training_programs: demoTrainingPrograms[0] },
  { id: 'asgn-002', status: 'in_progress', due_date: '2026-04-30', assigned_date: '2026-03-15', user_id: 'demo-driver-001', fleet_id: FLEET_ID, module_id: null, training_program_id: 'tp-002', assigned_by: 'demo-coach-001', priority: 'normal', reminders_sent: 1, created_at: '2026-03-15T00:00:00Z', profiles: demoProfiles[1], training_programs: demoTrainingPrograms[1] },
  { id: 'asgn-003', status: 'in_progress', due_date: '2026-04-20', assigned_date: '2026-03-01', user_id: 'demo-driver-002', fleet_id: FLEET_ID, module_id: null, training_program_id: 'tp-003', assigned_by: 'demo-sup-001', priority: 'high', reminders_sent: 2, created_at: '2026-03-01T00:00:00Z', profiles: demoProfiles[2], training_programs: demoTrainingPrograms[2] },
  { id: 'asgn-004', status: 'overdue', due_date: '2026-03-01', assigned_date: '2026-01-10', user_id: 'demo-driver-004', fleet_id: FLEET_ID, module_id: null, training_program_id: 'tp-001', assigned_by: 'demo-mgr-001', priority: 'urgent', reminders_sent: 4, created_at: '2026-01-10T00:00:00Z', profiles: demoProfiles[4], training_programs: demoTrainingPrograms[0] },
  { id: 'asgn-005', status: 'pending', due_date: '2026-05-15', assigned_date: '2026-04-01', user_id: 'demo-driver-005', fleet_id: FLEET_ID, module_id: null, training_program_id: 'tp-002', assigned_by: 'demo-user-jeremyw', priority: 'normal', reminders_sent: 0, created_at: '2026-04-01T00:00:00Z', profiles: demoProfiles[5], training_programs: demoTrainingPrograms[1] },
  { id: 'asgn-006', status: 'completed', due_date: '2026-01-31', assigned_date: '2025-12-15', user_id: 'demo-driver-003', fleet_id: FLEET_ID, module_id: null, training_program_id: 'tp-005', assigned_by: 'demo-sup-001', priority: 'normal', reminders_sent: 0, created_at: '2025-12-15T00:00:00Z', profiles: demoProfiles[3], training_programs: demoTrainingPrograms[4] },
  { id: 'asgn-007', status: 'completed', due_date: '2026-02-28', assigned_date: '2026-01-20', user_id: 'demo-driver-002', fleet_id: FLEET_ID, module_id: null, training_program_id: 'tp-001', assigned_by: 'demo-user-jeremyw', priority: 'high', reminders_sent: 0, created_at: '2026-01-20T00:00:00Z', profiles: demoProfiles[2], training_programs: demoTrainingPrograms[0] },
  { id: 'asgn-008', status: 'pending', due_date: '2026-05-01', assigned_date: '2026-04-03', user_id: 'demo-driver-003', fleet_id: FLEET_ID, module_id: null, training_program_id: 'tp-004', assigned_by: 'demo-mgr-001', priority: 'high', reminders_sent: 0, created_at: '2026-04-03T00:00:00Z', profiles: demoProfiles[3], training_programs: demoTrainingPrograms[3] },
]

export const demoNotifications: Notification[] = [
  { id: 'notif-001', title: 'CDL Expired', message: "Tony Lee's CDL has expired and needs immediate renewal.", notification_type: 'compliance_alert', is_read: false, user_id: 'demo-user-jeremyw', action_url: '/compliance', created_at: '2026-04-03T10:00:00Z' },
  { id: 'notif-002', title: 'Training Overdue', message: "Tony Lee's New Driver Orientation is overdue by 34 days.", notification_type: 'training_alert', is_read: false, user_id: 'demo-user-jeremyw', action_url: '/training', created_at: '2026-04-03T08:00:00Z' },
  { id: 'notif-003', title: 'Medical Card Expiring', message: "Sarah Johnson's medical card expires on May 20, 2026.", notification_type: 'compliance_alert', is_read: false, user_id: 'demo-user-jeremyw', action_url: '/compliance', created_at: '2026-04-02T09:00:00Z' },
  { id: 'notif-004', title: 'Training Completed', message: 'Marco Rodriguez completed New Driver Orientation with a 94% score.', notification_type: 'training_complete', is_read: true, user_id: 'demo-user-jeremyw', action_url: '/training', created_at: '2026-02-10T14:00:00Z' },
  { id: 'notif-005', title: 'Vehicle Inspection Due', message: 'BFC-R104 inspection is due on May 1, 2026.', notification_type: 'vehicle_alert', is_read: true, user_id: 'demo-user-jeremyw', action_url: '/vehicles', created_at: '2026-03-30T11:00:00Z' },
]

export const demoCompletionRecords: CompletionRecord[] = [
  { id: 'cr-001', completed_date: '2026-02-10', quiz_score: 94, user_id: 'demo-driver-001', fleet_id: FLEET_ID, lesson_id: null, module_id: null, assignment_id: 'asgn-001', time_spent: 450, attempts: 1, passed: true, created_at: '2026-02-10T00:00:00Z' },
  { id: 'cr-002', completed_date: '2026-01-28', quiz_score: 88, user_id: 'demo-driver-003', fleet_id: FLEET_ID, lesson_id: null, module_id: null, assignment_id: 'asgn-006', time_spent: 110, attempts: 1, passed: true, created_at: '2026-01-28T00:00:00Z' },
  { id: 'cr-003', completed_date: '2026-02-25', quiz_score: 91, user_id: 'demo-driver-002', fleet_id: FLEET_ID, lesson_id: null, module_id: null, assignment_id: 'asgn-007', time_spent: 460, attempts: 2, passed: true, created_at: '2026-02-25T00:00:00Z' },
]

export const demoDriverStats: DriverStats[] = [
  { id: 'ds-001', user_id: 'demo-driver-001', total_trainings_completed: 3, total_lessons_completed: 18, total_quizzes_taken: 5, average_quiz_score: 92, compliance_score: 100, overdue_count: 0, current_streak: 12, longest_streak: 20, updated_at: now },
  { id: 'ds-002', user_id: 'demo-driver-002', total_trainings_completed: 2, total_lessons_completed: 12, total_quizzes_taken: 3, average_quiz_score: 89, compliance_score: 85, overdue_count: 0, current_streak: 5, longest_streak: 15, updated_at: now },
  { id: 'ds-003', user_id: 'demo-driver-003', total_trainings_completed: 1, total_lessons_completed: 6, total_quizzes_taken: 2, average_quiz_score: 88, compliance_score: 100, overdue_count: 0, current_streak: 8, longest_streak: 8, updated_at: now },
  { id: 'ds-004', user_id: 'demo-driver-004', total_trainings_completed: 0, total_lessons_completed: 2, total_quizzes_taken: 1, average_quiz_score: 65, compliance_score: 40, overdue_count: 1, current_streak: 0, longest_streak: 3, updated_at: now },
  { id: 'ds-005', user_id: 'demo-driver-005', total_trainings_completed: 0, total_lessons_completed: 0, total_quizzes_taken: 0, average_quiz_score: null, compliance_score: 100, overdue_count: 0, current_streak: 0, longest_streak: 0, updated_at: now },
]

export function isDemoMode(): boolean {
  return !import.meta.env.VITE_SUPABASE_URL || import.meta.env.VITE_SUPABASE_URL === 'https://placeholder.supabase.co'
}

export const DEMO_FLEET_ID = FLEET_ID
