-- DOT-Copilot initial schema (baseline)
-- Generated 2026-07-26 by Claude (Cowork). Reconstructed from src/types/database.ts + the zod schemas.
-- This baseline was applied live to Supabase project yoqqgbhgycbmqveahrtd on 2026-07-26.
-- Idempotent (create ... if not exists / drop policy if exists), so it is safe to re-run.
--   * Fresh project:            supabase db push
--   * Already-provisioned proj: supabase migration repair --status applied 20260726003000

-- =====================================================================
-- Tables (dependency order)
-- =====================================================================
create table if not exists public.fleets (id uuid primary key default gen_random_uuid(), company_name text not null, locations text, cargo_type text, cdl_status text, vehicle_types text, key_risk_areas text, operation_type text, states_of_operation text, onboarding_completed boolean not null default false, compliance_profile_configured boolean not null default false, logo_url text, primary_color text, secondary_color text, default_language text not null default 'en', enable_sms_notifications boolean not null default false, enable_push_notifications boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.locations (id uuid primary key default gen_random_uuid(), name text not null, address text, city text, state text, zip_code text, fleet_id uuid not null references public.fleets(id) on delete cascade, is_active boolean not null default true, created_at timestamptz not null default now());
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, email text not null, name text, role text not null default 'DRIVER' check (role in ('DRIVER','DRIVER_COACH','SUPERVISOR','BRANCH_MANAGER','ADMIN')), fleet_id uuid references public.fleets(id) on delete set null, location_id uuid references public.locations(id) on delete set null, phone text, preferred_language text not null default 'en', timezone text not null default 'America/New_York', prefer_email boolean not null default true, prefer_sms boolean not null default false, prefer_push boolean not null default true, employee_id text, hire_date date, is_active boolean not null default true, last_login_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), is_platform_admin boolean not null default false);
create table if not exists public.compliance_requirements (id uuid primary key default gen_random_uuid(), name text not null, description text, regulatory_body text not null, required_hours numeric, renewal_period integer, applies_to text[] not null default '{}', is_active boolean not null default true, fleet_id uuid references public.fleets(id) on delete cascade, alert_days integer[] not null default '{}', created_at timestamptz not null default now());
create table if not exists public.training_programs (id uuid primary key default gen_random_uuid(), program_name text not null, description text, is_recommended boolean not null default false, fleet_id uuid not null references public.fleets(id) on delete cascade, is_template boolean not null default false, template_category text, estimated_duration integer, compliance_requirement_id uuid references public.compliance_requirements(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.modules (id uuid primary key default gen_random_uuid(), module_name text not null, description text, sequence_order integer not null default 0, fleet_id uuid not null references public.fleets(id) on delete cascade, training_program_id uuid not null references public.training_programs(id) on delete cascade, estimated_duration integer, passing_score integer not null default 80, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.lessons (id uuid primary key default gen_random_uuid(), lesson_name text not null, content text, content_type text not null default 'TEXT' check (content_type in ('VIDEO','PDF','POWERPOINT','SCORM','TEXT','IMAGE','QUICK_ACKNOWLEDGE')), file_url text, video_url text, video_duration integer, acknowledgment_text text, sequence_order integer not null default 0, requires_esignature boolean not null default false, fleet_id uuid not null references public.fleets(id) on delete cascade, module_id uuid not null references public.modules(id) on delete cascade, estimated_duration integer, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.assignments (id uuid primary key default gen_random_uuid(), status text not null default 'pending' check (status in ('pending','in_progress','completed','overdue')), due_date date, assigned_date timestamptz not null default now(), user_id uuid not null references public.profiles(id) on delete cascade, fleet_id uuid not null references public.fleets(id) on delete cascade, module_id uuid references public.modules(id) on delete set null, training_program_id uuid references public.training_programs(id) on delete set null, assigned_by uuid references public.profiles(id) on delete set null, priority text not null default 'normal' check (priority in ('low','normal','high','urgent')), reminders_sent integer not null default 0, created_at timestamptz not null default now());
create table if not exists public.completion_records (id uuid primary key default gen_random_uuid(), completed_date timestamptz not null default now(), quiz_score numeric, user_id uuid not null references public.profiles(id) on delete cascade, fleet_id uuid not null references public.fleets(id) on delete cascade, lesson_id uuid references public.lessons(id) on delete set null, module_id uuid references public.modules(id) on delete set null, assignment_id uuid references public.assignments(id) on delete set null, time_spent integer, attempts integer not null default 0, passed boolean not null default false, created_at timestamptz not null default now());
create table if not exists public.driver_compliance (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, requirement_id uuid not null references public.compliance_requirements(id) on delete cascade, status text not null default 'NOT_STARTED' check (status in ('COMPLIANT','EXPIRING_SOON','EXPIRED','NOT_STARTED','IN_PROGRESS','WAIVED')), completed_date date, expiration_date date, hours_completed numeric, certificate_url text, verified_by uuid references public.profiles(id) on delete set null, verified_at timestamptz, notes text, created_at timestamptz not null default now());
create table if not exists public.driver_documents (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, fleet_id uuid not null references public.fleets(id) on delete cascade, document_type text not null check (document_type in ('CDL','MEDICAL_CARD','HAZMAT_ENDORSEMENT','TWIC_CARD','PASSPORT','MVR','DRUG_TEST','BACKGROUND_CHECK','STATE_PERMIT','FOOD_HANDLER_CERT','REFRIGERATED_TRANSPORT_QUAL','OTHER')), document_number text, issued_date date, expiration_date date not null, issuing_state text, cdl_class text, endorsements text[] not null default '{}', restrictions text[] not null default '{}', status text not null default 'active', created_at timestamptz not null default now());
create table if not exists public.vehicles (id uuid primary key default gen_random_uuid(), fleet_id uuid not null references public.fleets(id) on delete cascade, vehicle_number text not null, vehicle_type text not null check (vehicle_type in ('refrigerated_truck','delivery_van','dry_goods_truck','box_truck','other')), make text, model text, year integer, license_plate text, has_temperature_monitoring boolean not null default false, last_inspection_date date, next_inspection_due date, assigned_route text, assigned_driver_id uuid references public.profiles(id) on delete set null, is_active boolean not null default true, notes text, created_at timestamptz not null default now());
create table if not exists public.notifications (id uuid primary key default gen_random_uuid(), message text not null, title text, notification_type text not null, channel text not null default 'IN_APP' check (channel in ('IN_APP','EMAIL','SMS','PUSH')), is_read boolean not null default false, is_sent boolean not null default false, sent_at timestamptz, user_id uuid not null references public.profiles(id) on delete cascade, fleet_id uuid references public.fleets(id) on delete set null, action_url text, action_label text, created_at timestamptz not null default now());
create table if not exists public.driver_stats (id uuid primary key default gen_random_uuid(), user_id uuid not null unique references public.profiles(id) on delete cascade, total_trainings_completed integer not null default 0, total_lessons_completed integer not null default 0, total_quizzes_taken integer not null default 0, average_quiz_score numeric, compliance_score numeric, overdue_count integer not null default 0, current_streak integer not null default 0, longest_streak integer not null default 0, updated_at timestamptz not null default now());
create table if not exists public.push_subscriptions (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, endpoint text not null, p256dh_key text not null, auth_key text not null, created_at timestamptz not null default now(), unique(user_id, endpoint));

-- =====================================================================
-- Helper functions (SECURITY DEFINER -> read caller role/fleet without RLS recursion)
-- =====================================================================
create or replace function public.app_fleet() returns uuid language sql stable security definer set search_path = public as $$ select fleet_id from public.profiles where id = auth.uid() $$;
create or replace function public.app_role() returns text language sql stable security definer set search_path = public as $$ select role from public.profiles where id = auth.uid() $$;
create or replace function public.app_is_platform_admin() returns boolean language sql stable security definer set search_path = public as $$ select coalesce(is_platform_admin, false) from public.profiles where id = auth.uid() $$;

-- signup -> profiles
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.profiles (id, email, name) values (new.id, new.email, coalesce(new.raw_user_meta_data->>'name', new.raw_user_meta_data->>'full_name')) on conflict (id) do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

-- updated_at maintenance
create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;
drop trigger if exists trg_fleets_updated on public.fleets; create trigger trg_fleets_updated before update on public.fleets for each row execute function public.set_updated_at();
drop trigger if exists trg_profiles_updated on public.profiles; create trigger trg_profiles_updated before update on public.profiles for each row execute function public.set_updated_at();
drop trigger if exists trg_tp_updated on public.training_programs; create trigger trg_tp_updated before update on public.training_programs for each row execute function public.set_updated_at();
drop trigger if exists trg_modules_updated on public.modules; create trigger trg_modules_updated before update on public.modules for each row execute function public.set_updated_at();
drop trigger if exists trg_lessons_updated on public.lessons; create trigger trg_lessons_updated before update on public.lessons for each row execute function public.set_updated_at();
drop trigger if exists trg_stats_updated on public.driver_stats; create trigger trg_stats_updated before update on public.driver_stats for each row execute function public.set_updated_at();

-- =====================================================================
-- RLS + grants + indexes
-- =====================================================================
do $$ declare t text; begin foreach t in array array['fleets','locations','profiles','compliance_requirements','training_programs','modules','lessons','assignments','completion_records','driver_compliance','driver_documents','vehicles','notifications','driver_stats','push_subscriptions'] loop execute format('alter table public.%I enable row level security', t); end loop; end $$;
grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
create index if not exists idx_profiles_fleet on public.profiles(fleet_id);
create index if not exists idx_vehicles_fleet on public.vehicles(fleet_id);
create index if not exists idx_assignments_user on public.assignments(user_id);
create index if not exists idx_assignments_fleet on public.assignments(fleet_id);
create index if not exists idx_notifications_user on public.notifications(user_id);
create index if not exists idx_driver_compliance_user on public.driver_compliance(user_id);
create index if not exists idx_driver_documents_user on public.driver_documents(user_id);
create index if not exists idx_completion_user on public.completion_records(user_id);

-- =====================================================================
-- Policies (capability model mirrors src/hooks/usePermissions.ts)
--   manage users = ADMIN/BRANCH_MANAGER; vehicles/compliance +SUPERVISOR;
--   training +DRIVER_COACH; users own their personal rows; platform admins cross-fleet.
-- =====================================================================
drop policy if exists profiles_select on public.profiles; create policy profiles_select on public.profiles for select using (public.app_is_platform_admin() or id = auth.uid() or fleet_id = public.app_fleet());
drop policy if exists profiles_insert on public.profiles; create policy profiles_insert on public.profiles for insert with check (public.app_is_platform_admin() or (public.app_role() in ('ADMIN','BRANCH_MANAGER') and fleet_id = public.app_fleet()));
drop policy if exists profiles_update on public.profiles; create policy profiles_update on public.profiles for update using (public.app_is_platform_admin() or id = auth.uid() or (public.app_role() in ('ADMIN','BRANCH_MANAGER') and fleet_id = public.app_fleet())) with check (public.app_is_platform_admin() or id = auth.uid() or (public.app_role() in ('ADMIN','BRANCH_MANAGER') and fleet_id = public.app_fleet()));
drop policy if exists profiles_delete on public.profiles; create policy profiles_delete on public.profiles for delete using (public.app_is_platform_admin() or (public.app_role() in ('ADMIN','BRANCH_MANAGER') and fleet_id = public.app_fleet()));
drop policy if exists fleets_select on public.fleets; create policy fleets_select on public.fleets for select using (public.app_is_platform_admin() or id = public.app_fleet());
drop policy if exists fleets_insert on public.fleets; create policy fleets_insert on public.fleets for insert with check (public.app_is_platform_admin() or public.app_role() in ('ADMIN','BRANCH_MANAGER'));
drop policy if exists fleets_update on public.fleets; create policy fleets_update on public.fleets for update using (public.app_is_platform_admin() or (public.app_role() in ('ADMIN','BRANCH_MANAGER') and id = public.app_fleet())) with check (public.app_is_platform_admin() or (public.app_role() in ('ADMIN','BRANCH_MANAGER') and id = public.app_fleet()));
drop policy if exists fleets_delete on public.fleets; create policy fleets_delete on public.fleets for delete using (public.app_is_platform_admin());
drop policy if exists locations_read on public.locations; create policy locations_read on public.locations for select using (public.app_is_platform_admin() or fleet_id = public.app_fleet());
drop policy if exists locations_manage on public.locations; create policy locations_manage on public.locations for all using (public.app_is_platform_admin() or (public.app_role() in ('ADMIN','BRANCH_MANAGER') and fleet_id = public.app_fleet())) with check (public.app_is_platform_admin() or (public.app_role() in ('ADMIN','BRANCH_MANAGER') and fleet_id = public.app_fleet()));
drop policy if exists cr_read on public.compliance_requirements; create policy cr_read on public.compliance_requirements for select using (public.app_is_platform_admin() or fleet_id is null or fleet_id = public.app_fleet());
drop policy if exists cr_manage on public.compliance_requirements; create policy cr_manage on public.compliance_requirements for all using (public.app_is_platform_admin() or (public.app_role() in ('ADMIN','BRANCH_MANAGER','SUPERVISOR') and fleet_id = public.app_fleet())) with check (public.app_is_platform_admin() or (public.app_role() in ('ADMIN','BRANCH_MANAGER','SUPERVISOR') and fleet_id = public.app_fleet()));
drop policy if exists tp_read on public.training_programs; create policy tp_read on public.training_programs for select using (public.app_is_platform_admin() or fleet_id = public.app_fleet());
drop policy if exists tp_manage on public.training_programs; create policy tp_manage on public.training_programs for all using (public.app_is_platform_admin() or (public.app_role() in ('ADMIN','BRANCH_MANAGER','SUPERVISOR','DRIVER_COACH') and fleet_id = public.app_fleet())) with check (public.app_is_platform_admin() or (public.app_role() in ('ADMIN','BRANCH_MANAGER','SUPERVISOR','DRIVER_COACH') and fleet_id = public.app_fleet()));
drop policy if exists modules_read on public.modules; create policy modules_read on public.modules for select using (public.app_is_platform_admin() or fleet_id = public.app_fleet());
drop policy if exists modules_manage on public.modules; create policy modules_manage on public.modules for all using (public.app_is_platform_admin() or (public.app_role() in ('ADMIN','BRANCH_MANAGER','SUPERVISOR','DRIVER_COACH') and fleet_id = public.app_fleet())) with check (public.app_is_platform_admin() or (public.app_role() in ('ADMIN','BRANCH_MANAGER','SUPERVISOR','DRIVER_COACH') and fleet_id = public.app_fleet()));
drop policy if exists lessons_read on public.lessons; create policy lessons_read on public.lessons for select using (public.app_is_platform_admin() or fleet_id = public.app_fleet());
drop policy if exists lessons_manage on public.lessons; create policy lessons_manage on public.lessons for all using (public.app_is_platform_admin() or (public.app_role() in ('ADMIN','BRANCH_MANAGER','SUPERVISOR','DRIVER_COACH') and fleet_id = public.app_fleet())) with check (public.app_is_platform_admin() or (public.app_role() in ('ADMIN','BRANCH_MANAGER','SUPERVISOR','DRIVER_COACH') and fleet_id = public.app_fleet()));
drop policy if exists vehicles_read on public.vehicles; create policy vehicles_read on public.vehicles for select using (public.app_is_platform_admin() or fleet_id = public.app_fleet());
drop policy if exists vehicles_manage on public.vehicles; create policy vehicles_manage on public.vehicles for all using (public.app_is_platform_admin() or (public.app_role() in ('ADMIN','BRANCH_MANAGER','SUPERVISOR') and fleet_id = public.app_fleet())) with check (public.app_is_platform_admin() or (public.app_role() in ('ADMIN','BRANCH_MANAGER','SUPERVISOR') and fleet_id = public.app_fleet()));
drop policy if exists assignments_read on public.assignments; create policy assignments_read on public.assignments for select using (public.app_is_platform_admin() or user_id = auth.uid() or (fleet_id = public.app_fleet() and public.app_role() in ('ADMIN','BRANCH_MANAGER','SUPERVISOR','DRIVER_COACH')));
drop policy if exists assignments_manage on public.assignments; create policy assignments_manage on public.assignments for all using (public.app_is_platform_admin() or (fleet_id = public.app_fleet() and public.app_role() in ('ADMIN','BRANCH_MANAGER','SUPERVISOR','DRIVER_COACH'))) with check (public.app_is_platform_admin() or (fleet_id = public.app_fleet() and public.app_role() in ('ADMIN','BRANCH_MANAGER','SUPERVISOR','DRIVER_COACH')));
drop policy if exists assignments_update_own on public.assignments; create policy assignments_update_own on public.assignments for update using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists crec_read on public.completion_records; create policy crec_read on public.completion_records for select using (public.app_is_platform_admin() or user_id = auth.uid() or (fleet_id = public.app_fleet() and public.app_role() in ('ADMIN','BRANCH_MANAGER','SUPERVISOR','DRIVER_COACH')));
drop policy if exists crec_insert_own on public.completion_records; create policy crec_insert_own on public.completion_records for insert with check (user_id = auth.uid() or public.app_is_platform_admin() or (fleet_id = public.app_fleet() and public.app_role() in ('ADMIN','BRANCH_MANAGER','SUPERVISOR','DRIVER_COACH')));
drop policy if exists crec_manage on public.completion_records; create policy crec_manage on public.completion_records for all using (public.app_is_platform_admin() or (fleet_id = public.app_fleet() and public.app_role() in ('ADMIN','BRANCH_MANAGER','SUPERVISOR','DRIVER_COACH'))) with check (public.app_is_platform_admin() or (fleet_id = public.app_fleet() and public.app_role() in ('ADMIN','BRANCH_MANAGER','SUPERVISOR','DRIVER_COACH')));
drop policy if exists dc_read on public.driver_compliance; create policy dc_read on public.driver_compliance for select using (public.app_is_platform_admin() or user_id = auth.uid() or (public.app_role() in ('ADMIN','BRANCH_MANAGER','SUPERVISOR') and exists (select 1 from public.profiles p where p.id = driver_compliance.user_id and p.fleet_id = public.app_fleet())));
drop policy if exists dc_manage on public.driver_compliance; create policy dc_manage on public.driver_compliance for all using (public.app_is_platform_admin() or (public.app_role() in ('ADMIN','BRANCH_MANAGER','SUPERVISOR') and exists (select 1 from public.profiles p where p.id = driver_compliance.user_id and p.fleet_id = public.app_fleet()))) with check (public.app_is_platform_admin() or (public.app_role() in ('ADMIN','BRANCH_MANAGER','SUPERVISOR') and exists (select 1 from public.profiles p where p.id = driver_compliance.user_id and p.fleet_id = public.app_fleet())));
drop policy if exists dd_read on public.driver_documents; create policy dd_read on public.driver_documents for select using (public.app_is_platform_admin() or user_id = auth.uid() or (fleet_id = public.app_fleet() and public.app_role() in ('ADMIN','BRANCH_MANAGER','SUPERVISOR')));
drop policy if exists dd_manage on public.driver_documents; create policy dd_manage on public.driver_documents for all using (public.app_is_platform_admin() or user_id = auth.uid() or (fleet_id = public.app_fleet() and public.app_role() in ('ADMIN','BRANCH_MANAGER','SUPERVISOR'))) with check (public.app_is_platform_admin() or user_id = auth.uid() or (fleet_id = public.app_fleet() and public.app_role() in ('ADMIN','BRANCH_MANAGER','SUPERVISOR')));
drop policy if exists notif_read on public.notifications; create policy notif_read on public.notifications for select using (public.app_is_platform_admin() or user_id = auth.uid());
drop policy if exists notif_insert on public.notifications; create policy notif_insert on public.notifications for insert with check (public.app_is_platform_admin() or user_id = auth.uid() or (fleet_id = public.app_fleet() and public.app_role() in ('ADMIN','BRANCH_MANAGER','SUPERVISOR')));
drop policy if exists notif_update_own on public.notifications; create policy notif_update_own on public.notifications for update using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists notif_delete_own on public.notifications; create policy notif_delete_own on public.notifications for delete using (public.app_is_platform_admin() or user_id = auth.uid());
drop policy if exists ds_read on public.driver_stats; create policy ds_read on public.driver_stats for select using (public.app_is_platform_admin() or user_id = auth.uid() or (public.app_role() in ('ADMIN','BRANCH_MANAGER','SUPERVISOR') and exists (select 1 from public.profiles p where p.id = driver_stats.user_id and p.fleet_id = public.app_fleet())));
drop policy if exists ds_manage on public.driver_stats; create policy ds_manage on public.driver_stats for all using (public.app_is_platform_admin() or user_id = auth.uid() or (public.app_role() in ('ADMIN','BRANCH_MANAGER','SUPERVISOR') and exists (select 1 from public.profiles p where p.id = driver_stats.user_id and p.fleet_id = public.app_fleet()))) with check (public.app_is_platform_admin() or user_id = auth.uid() or (public.app_role() in ('ADMIN','BRANCH_MANAGER','SUPERVISOR') and exists (select 1 from public.profiles p where p.id = driver_stats.user_id and p.fleet_id = public.app_fleet())));
drop policy if exists push_own on public.push_subscriptions; create policy push_own on public.push_subscriptions for all using (user_id = auth.uid()) with check (user_id = auth.uid());
